# Generated by Django 4.2.4 on 2023-10-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Anonymous', max_length=50, verbose_name='Name')),
                ('body', models.TextField(db_index=True, verbose_name='Body')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created DateField')),
            ],
            options={
                'db_table': 'createReview',
            },
        ),
    ]
